# =====================================================================
# Crossplane Claim — XPostgreSQLInstance
# =====================================================================
apiVersion: database.poc.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: mi-base-de-datos
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  dbName: "ventas_db"
  owner: "equipo-backend"